// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCOw7ZLcpzygMC7HV3KEgSY-8Slp96ATrM',
    appId: '1:443346353178:web:fff89d41ac8342a3fd65a3',
    messagingSenderId: '443346353178',
    projectId: 'fooddelivery-297a9',
    authDomain: 'fooddelivery-297a9.firebaseapp.com',
    storageBucket: 'fooddelivery-297a9.firebasestorage.app',
    measurementId: 'G-7227QVZQCC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB_X3Izdvi4WTfRFt0YydtIqlZJZqH0edE',
    appId: '1:443346353178:android:ffa541abb530c74cfd65a3',
    messagingSenderId: '443346353178',
    projectId: 'fooddelivery-297a9',
    storageBucket: 'fooddelivery-297a9.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDuaINrFTK3_6lJpdY8ngnyQ81mSzymtlA',
    appId: '1:443346353178:ios:911c53e5ab2072bdfd65a3',
    messagingSenderId: '443346353178',
    projectId: 'fooddelivery-297a9',
    storageBucket: 'fooddelivery-297a9.firebasestorage.app',
    iosBundleId: 'com.example.foodApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDuaINrFTK3_6lJpdY8ngnyQ81mSzymtlA',
    appId: '1:443346353178:ios:911c53e5ab2072bdfd65a3',
    messagingSenderId: '443346353178',
    projectId: 'fooddelivery-297a9',
    storageBucket: 'fooddelivery-297a9.firebasestorage.app',
    iosBundleId: 'com.example.foodApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCOw7ZLcpzygMC7HV3KEgSY-8Slp96ATrM',
    appId: '1:443346353178:web:ce94044ccddb5f95fd65a3',
    messagingSenderId: '443346353178',
    projectId: 'fooddelivery-297a9',
    authDomain: 'fooddelivery-297a9.firebaseapp.com',
    storageBucket: 'fooddelivery-297a9.firebasestorage.app',
    measurementId: 'G-SPHB7D8JH1',
  );
}
